kind: containers
meta:
  name: nginx
  group: examples
spec:
  ghost:
    meta:
      name: nginx
      group: examples
      labels:
        "traefik.enable": "true"
        "traefik.http.routers.qdnqn-ghost.rule": "Host(`example.com`)"
        "traefik.http.routers.qdnqn-ghost.entrypoints": "websecure"
        "traefik.http.routers.qdnqn-ghost.tls.certresolver": "myresolver"
        "traefik.http.services.qdnqn-ghost-service.loadbalancer.server.port": "80"
    spec:
      container:
        image: "nginx"
        tag: "latest"
        replicas: 1
        ports:
          - container: "8080"